# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jesse_brown/github-classroom/rmit-computing-technologies/cosc2804-sep-23-assignment-2-mckey6/mcpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jesse_brown/github-classroom/rmit-computing-technologies/cosc2804-sep-23-assignment-2-mckey6/mcpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jesse_brown/github-classroom/rmit-computing-technologies/cosc2804-sep-23-assignment-2-mckey6/mcpp/CMakeFiles /home/jesse_brown/github-classroom/rmit-computing-technologies/cosc2804-sep-23-assignment-2-mckey6/mcpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jesse_brown/github-classroom/rmit-computing-technologies/cosc2804-sep-23-assignment-2-mckey6/mcpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mcpp

# Build rule for target.
mcpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mcpp
.PHONY : mcpp

# fast build rule for target.
mcpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcpp.dir/build.make CMakeFiles/mcpp.dir/build
.PHONY : mcpp/fast

#=============================================================================
# Target rules for targets named local_tests

# Build rule for target.
local_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 local_tests
.PHONY : local_tests

# fast build rule for target.
local_tests/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/local_tests.dir/build.make test/CMakeFiles/local_tests.dir/build
.PHONY : local_tests/fast

#=============================================================================
# Target rules for targets named test_suite

# Build rule for target.
test_suite: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_suite
.PHONY : test_suite

# fast build rule for target.
test_suite/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_suite.dir/build.make test/CMakeFiles/test_suite.dir/build
.PHONY : test_suite/fast

src/block.o: src/block.cpp.o
.PHONY : src/block.o

# target to build an object file
src/block.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcpp.dir/build.make CMakeFiles/mcpp.dir/src/block.cpp.o
.PHONY : src/block.cpp.o

src/block.i: src/block.cpp.i
.PHONY : src/block.i

# target to preprocess a source file
src/block.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcpp.dir/build.make CMakeFiles/mcpp.dir/src/block.cpp.i
.PHONY : src/block.cpp.i

src/block.s: src/block.cpp.s
.PHONY : src/block.s

# target to generate assembly for a file
src/block.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcpp.dir/build.make CMakeFiles/mcpp.dir/src/block.cpp.s
.PHONY : src/block.cpp.s

src/connection.o: src/connection.cpp.o
.PHONY : src/connection.o

# target to build an object file
src/connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcpp.dir/build.make CMakeFiles/mcpp.dir/src/connection.cpp.o
.PHONY : src/connection.cpp.o

src/connection.i: src/connection.cpp.i
.PHONY : src/connection.i

# target to preprocess a source file
src/connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcpp.dir/build.make CMakeFiles/mcpp.dir/src/connection.cpp.i
.PHONY : src/connection.cpp.i

src/connection.s: src/connection.cpp.s
.PHONY : src/connection.s

# target to generate assembly for a file
src/connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcpp.dir/build.make CMakeFiles/mcpp.dir/src/connection.cpp.s
.PHONY : src/connection.cpp.s

src/mcpp.o: src/mcpp.cpp.o
.PHONY : src/mcpp.o

# target to build an object file
src/mcpp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcpp.dir/build.make CMakeFiles/mcpp.dir/src/mcpp.cpp.o
.PHONY : src/mcpp.cpp.o

src/mcpp.i: src/mcpp.cpp.i
.PHONY : src/mcpp.i

# target to preprocess a source file
src/mcpp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcpp.dir/build.make CMakeFiles/mcpp.dir/src/mcpp.cpp.i
.PHONY : src/mcpp.cpp.i

src/mcpp.s: src/mcpp.cpp.s
.PHONY : src/mcpp.s

# target to generate assembly for a file
src/mcpp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcpp.dir/build.make CMakeFiles/mcpp.dir/src/mcpp.cpp.s
.PHONY : src/mcpp.cpp.s

src/util.o: src/util.cpp.o
.PHONY : src/util.o

# target to build an object file
src/util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcpp.dir/build.make CMakeFiles/mcpp.dir/src/util.cpp.o
.PHONY : src/util.cpp.o

src/util.i: src/util.cpp.i
.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcpp.dir/build.make CMakeFiles/mcpp.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s
.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcpp.dir/build.make CMakeFiles/mcpp.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... local_tests"
	@echo "... mcpp"
	@echo "... test_suite"
	@echo "... src/block.o"
	@echo "... src/block.i"
	@echo "... src/block.s"
	@echo "... src/connection.o"
	@echo "... src/connection.i"
	@echo "... src/connection.s"
	@echo "... src/mcpp.o"
	@echo "... src/mcpp.i"
	@echo "... src/mcpp.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

